import { MenuItem, TextField } from "@mui/material";
import Head from "next/head";
import styled from "styled-components";

const Container = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;
  max-width: 600px;
  justify-self: center;
`;

const Title = styled.h1`
  color: blue;
`;

const Subtitle = styled.h2`
  color: blue;
`;

const Row = styled.div`
  margin-top: 32px;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
`;

export default function Home({
  title,
  subtitle,
}: {
  title: string;
  subtitle: string;
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Title>{title}</Title>
        <Subtitle>{subtitle}</Subtitle>
        <Row>
          <TextField id="outlined-basic" label="Outlined" variant="outlined" />
          <TextField
            error
            id="outlined-error-helper-text"
            label="Error"
            defaultValue="Hello World"
            helperText="Incorrect entry."
          />
        </Row>
        <Row>
          <TextField
            id="outlined-select-currency"
            select
            label="Select"
            defaultValue="EUR"
            helperText="Please select your currency"
          >
            {[
              {
                value: "USD",
                label: "$",
              },
              {
                value: "EUR",
                label: "€",
              },
              {
                value: "BTC",
                label: "฿",
              },
              {
                value: "JPY",
                label: "¥",
              },
            ].map((option) => (
              <MenuItem key={option.value} value={option.value}>
                {option.label}
              </MenuItem>
            ))}
          </TextField>
          <TextField
            error
            id="outlined-select-currency-error"
            select
            label="Select"
            defaultValue="EUR"
            helperText="Please select your currency"
          >
            {[
              {
                value: "USD",
                label: "$",
              },
              {
                value: "EUR",
                label: "€",
              },
              {
                value: "BTC",
                label: "฿",
              },
              {
                value: "JPY",
                label: "¥",
              },
            ].map((option) => (
              <MenuItem key={option.value} value={option.value}>
                {option.label}
              </MenuItem>
            ))}
          </TextField>
        </Row>
      </Container>
    </>
  );
}

export const getServerSideProps = async () => {
  return {
    props: {
      title: "Material Design",
      subtitle: "With Next.js and Styled Components",
    },
  };
};
